//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于英学 的本地化字符串。
        /// </summary>
        internal static string n_about {
            get {
                return ResourceManager.GetString("n_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教材与课程 的本地化字符串。
        /// </summary>
        internal static string n_course {
            get {
                return ResourceManager.GetString("n_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学校环境 的本地化字符串。
        /// </summary>
        internal static string n_environment {
            get {
                return ResourceManager.GetString("n_environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string n_home {
            get {
                return ResourceManager.GetString("n_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雅思考试 的本地化字符串。
        /// </summary>
        internal static string n_ielts {
            get {
                return ResourceManager.GetString("n_ielts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 招商加盟 的本地化字符串。
        /// </summary>
        internal static string n_join {
            get {
                return ResourceManager.GetString("n_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置： 的本地化字符串。
        /// </summary>
        internal static string n_location {
            get {
                return ResourceManager.GetString("n_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出国留学 的本地化字符串。
        /// </summary>
        internal static string n_study {
            get {
                return ResourceManager.GetString("n_study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 师资团队 的本地化字符串。
        /// </summary>
        internal static string n_team {
            get {
                return ResourceManager.GetString("n_team", resourceCulture);
            }
        }
    }
}
